version: '3.7'
services:
  mage-bit-node-js:
    container_name: node-js
    # image: node:alpine
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    tty: true
    volumes: 
      - ./app/frontend/. :/var/www
    ports:
      - "3333:3000"
    env_file:
      - ./app/frontend/.env