version: '3.7'
services:

  mage-bit-client-nginx:
    container_name: mage-bit-client-nginx
    build:
      context: .       # (!) Dockerfile doesn't see anything outside of this context
      dockerfile: ./docker/nginx-client-server/Dockerfile
    restart: always
    ports:
      - 3333:80
    volumes:
      - ./app/client:/var/www
      - ./docker/nginx-client-server/etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
  
  mage-bit-server-nginx:
    container_name: mage-bit-server-nginx
    build:
      context: .    
      dockerfile: ./docker/nginx-backend-server/Dockerfile
    restart: always
    ports:
      - 31243:80
    volumes:
      - ./app/server:/var/www
      - ./docker/nginx-backend-server/etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - mage-bit-php

  # MySQL server
  mage-bit-mysql:
    image: mysql:5.7
    container_name: mage-bit-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
     - db_data:/var/lib/mysql
    ports:
      - "17271:3306"
    environment:
      MYSQL_DATABASE: mage-bit
      MYSQL_ROOT_PASSWORD: test
    networks:
      - app-network
      - phpmyadmin-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mage-bit-mysql
      PMA_PASSWORD: test
    depends_on:
      - mage-bit-mysql
    ports:
      - "8080:80"
    networks:
      - phpmyadmin-network

  # PHP server
  mage-bit-php:
    build:
      context: .        
      dockerfile: ./docker/php-server/Dockerfile
    container_name: mage-bit-php
    restart: always
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app/server:/var/www
    networks:
      - app-network
    depends_on:
      - mage-bit-mysql

# Networks
networks:
  app-network:
    driver: bridge
  phpmyadmin-network:
    driver: bridge

# Volumes
volumes:
  db_data:
    driver: local
